const http = require('http');
const fs = require('fs');
const path = require('path');
const PORT = process.env.PORT || 3000;
const zlib=require('zlib'); const parks=JSON.parse(zlib.gunzipSync(Buffer.from(require('./data1.js')+require('./data2.js')+require('./data3.js')+require('./data4.js'),'base64')).toString());
const css=require('./css1.js')+require('./css2.js');
const js='';
const esc = s => String(s ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const pine = r => `${'▲'.repeat(Math.floor(r))}${r%1?'△':''} ${r.toFixed(1)}`;
function layout(title, body, desc='Reviews of all 116 Minnesota and Wisconsin state parks.'){
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><style>${css}</style></head><body><header class="site-header"><a class="brand" href="/">STATE PARKS.<span>MN & WI</span></a><nav><a href="/parks">Parks</a><a href="/about">About</a></nav></header>${body}<footer><strong>STATE PARKS.</strong><span>116 parks. Two states. Every one visited.</span></footer><script>${js}</script></body></html>`;
}
function card(p){return `<a class="park-card" href="/parks/${p.slug}"><div class="card-photo placeholder"><span>${esc(p.state)}</span></div><div class="card-body"><div class="eyebrow">${esc(p.city)}, ${esc(p.state)}</div><h3>${esc(p.name)}</h3><div class="rating">${pine(p.rating)}</div><div class="trip">${esc(p.idealTrip)}</div></div></a>`}
function home(){
 const featured=['tettegouche','copper-falls','bear-head-lake'].map(s=>parks.find(p=>p.slug===s)).filter(Boolean);
 return layout('State Parks — Minnesota & Wisconsin',`<main><section class="hero"><div><div class="kicker">A COMPLETED PARK PROJECT</div><h1>116 parks.<br>Two states.<br>Every one visited.</h1><p>Candid reviews of every designated state park in Minnesota and Wisconsin, based on actually going there.</p><div class="actions"><a class="button" href="/parks">Explore all parks</a><a class="button ghost" href="/about">About the project</a></div></div><div class="hero-stat"><strong>116</strong><span>STATE PARKS</span><div><b>66</b> Minnesota</div><div><b>50</b> Wisconsin</div></div></section><section class="section"><div class="section-head"><div><div class="kicker">START EXPLORING</div><h2>Find your kind of park.</h2></div></div><div class="trip-grid"><a href="/parks?trip=Weekend"><b>Weekend</b><span>Make a trip of it.</span></a><a href="/parks?trip=Day%20trip"><b>Day Trip</b><span>Worth a dedicated visit.</span></a><a href="/parks?trip=On%20the%20way"><b>On the Way</b><span>Stop when you're nearby.</span></a></div></section><section class="section"><div class="section-head"><div><div class="kicker">A FEW FAVORITES</div><h2>Featured parks.</h2></div><a href="/parks">See all 116 →</a></div><div class="cards">${featured.map(card).join('')}</div></section></main>`);
}
function parksPage(url){const state=url.searchParams.get('state')||'';const trip=url.searchParams.get('trip')||'';const q=(url.searchParams.get('q')||'').toLowerCase();let list=parks.filter(p=>(!state||p.state===state)&&(!trip||p.idealTrip.toLowerCase()===trip.toLowerCase())&&(!q||[p.name,p.city,p.state,p.review,p.pros,p.cons,p.criticalFactors].join(' ').toLowerCase().includes(q)));return layout('Explore Parks — MN & WI State Parks',`<main class="narrow"><section class="page-intro"><div class="kicker">EXPLORE</div><h1>All 116 parks.</h1><p>Browse every park from the original project.</p></section><form class="filters" method="get"><input name="q" value="${esc(url.searchParams.get('q')||'')}" placeholder="Search parks, places, waterfalls, camping..."><select name="state"><option value="">Both states</option><option value="MN" ${state==='MN'?'selected':''}>Minnesota</option><option value="WI" ${state==='WI'?'selected':''}>Wisconsin</option></select><select name="trip"><option value="">Any trip</option>${['Weekend','Day trip','On the way'].map(x=>`<option ${trip.toLowerCase()===x.toLowerCase()?'selected':''}>${x}</option>`).join('')}</select><button>Filter</button></form><div class="results-count">${list.length} parks</div><div class="cards">${list.map(card).join('')}</div></main>`)}
function parkPage(p){if(!p)return null;return layout(`${p.name} Review | MN & WI State Parks`,`<main class="park-page"><section class="park-hero"><div class="park-hero-copy"><a href="/parks" class="back">← All parks</a><div class="eyebrow">${esc(p.city)}, ${esc(p.state)}</div><h1>${esc(p.name)}</h1><div class="rating large">${pine(p.rating)}</div><div class="trip-pill">Ideal Trip: ${esc(p.idealTrip)}</div></div><div class="park-photo placeholder big"><span>${esc(p.state)}</span></div></section><section class="review-grid"><article><div class="kicker">THE REVIEW</div><p class="review">${esc(p.review)}</p><p class="source-note">Original booklet entry · page ${p.sourcePage}</p></article><aside><div class="fact"><b>PROS</b><span>${esc(p.pros)}</span></div><div class="fact"><b>CONS</b><span>${esc(p.cons)}</span></div><div class="fact"><b>CRITICAL FACTORS</b><span>${esc(p.criticalFactors)}</span></div></aside></section></main>`,p.review)}
function about(){return layout('About the Project | MN & WI State Parks',`<main class="narrow"><section class="page-intro"><div class="kicker">THE PROJECT</div><h1>Every designated state park in Minnesota and Wisconsin.</h1><p>This site grew out of a completed personal project and the review booklet that followed it.</p></section><section class="prose"><h2>About the reviews</h2><p>The reviews are candid impressions from actual visits, generally between April and October, usually in fair weather and often for only a few hours. They were written as practical advice for someone considering a visit—not as official park guides.</p><h2>The pine ratings</h2><p>Each park is rated up to five pine trees, with half-pine increments. The ratings are not intended as a ranking between parks; they reflect the quality of what each individual park has to offer.</p><h2>Ideal Trip</h2><p><b>Weekend</b> means the park has enough to justify spending substantial time there. <b>Day trip</b> means it is worth a dedicated visit when reasonably nearby. <b>On the way</b> means it is a worthwhile stop when passing through.</p></section></main>`)}
http.createServer((req,res)=>{let url;try{url=new URL(req.url,'http://localhost')}catch{return res.end()};let out,status=200;if(url.pathname==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,version:'0.5.1',parks:parks.length}));}if(url.pathname==='/')out=home();else if(url.pathname==='/parks')out=parksPage(url);else if(url.pathname==='/about')out=about();else if(url.pathname.startsWith('/parks/'))out=parkPage(parks.find(p=>p.slug===url.pathname.split('/')[2]));if(!out){status=404;out=layout('Not found','<main class="narrow"><section class="page-intro"><h1>Park not found.</h1><p><a href="/parks">Browse all parks</a></p></section></main>')}res.writeHead(status,{'content-type':'text/html; charset=utf-8'});res.end(out)}).listen(PORT,'0.0.0.0',()=>console.log(`State Parks v0.5.1 on ${PORT}`));
