(()=>{
  const TRIPS='mnwiTripCollections';
  const read=()=>{try{return JSON.parse(localStorage.getItem(TRIPS)||'[]')}catch{return[]}};
  const write=v=>localStorage.setItem(TRIPS,JSON.stringify(v));
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const page=document.querySelector('[data-page="trip"]');
  if(!page)return;
  const id=page.dataset.tripId;
  const dataNode=document.getElementById('parksData');
  const parks=dataNode?JSON.parse(dataNode.textContent):[];
  const details=window.PARK_DETAILS||{};
  const getTrip=()=>read().find(t=>t.id===id);
  const parkDetail=p=>details[p.slug]||{};
  const parkAddress=p=>parkDetail(p).address||'';
  const placeQuery=p=>parkDetail(p).mapsQuery||[(/\bpark\b/i.test(p.name)?p.name:p.name+' State Park'),p.city,p.state].filter(Boolean).join(', ');
  const placeUrl=p=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(placeQuery(p));
  const mapsUrl=stops=>{if(!stops.length)return'';if(stops.length===1)return placeUrl(stops[0]);const origin=placeQuery(stops[0]),destination=placeQuery(stops[stops.length-1]),mid=stops.slice(1,-1).map(placeQuery);let u='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(origin)+'&destination='+encodeURIComponent(destination)+'&travelmode=driving';if(mid.length)u+='&waypoints='+encodeURIComponent(mid.join('|'));return u};
  const grouped=trip=>{const out=[];(trip.parks||[]).map(s=>parks.find(p=>p.slug===s)).filter(Boolean).forEach(p=>{const d=String((trip.stopMeta&&trip.stopMeta[p.slug]||{}).day||'').trim()||'Unassigned';let g=out.find(x=>x.key===d);if(!g){g={key:d,stops:[]};out.push(g)}g.stops.push(p)});out.sort((a,b)=>{if(a.key==='Unassigned')return 1;if(b.key==='Unassigned')return-1;return Number(a.key)-Number(b.key)||a.key.localeCompare(b.key,undefined,{numeric:true})});return out};

  const css=document.createElement('style');
  css.textContent='.trip-detail-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:0 0 14px}.trip-detail-status{font-size:12px;color:#47745b}.trip-detail-editor{grid-column:1/-1;background:#f7f7f4;border:1px solid #e1e4e6;padding:12px;display:grid;grid-template-columns:1.5fr 1fr 1fr 1fr;gap:10px;align-items:end}.trip-detail-editor .wide{grid-column:span 2}.trip-detail-editor .full{grid-column:1/-1}.trip-detail-editor label>span,.park-address-block>span{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.1em;font-weight:800;color:#667;margin-bottom:4px}.trip-detail-editor input[type="text"],.trip-detail-editor input[type="date"],.trip-detail-editor input[type="time"]{width:100%;border:1px solid #d7dde1;padding:9px;background:#fff;font:inherit}.park-address-readonly{font-size:12px;line-height:1.35;color:#41505d;padding:8px 10px;background:#fff;border:1px solid #d7dde1;min-height:36px}.park-address-readonly a{color:#00558a;font-weight:700}.camp-toggle{display:flex;gap:7px;align-items:center;padding:9px 0;white-space:nowrap}.camp-toggle input{width:auto}.camp-hidden{display:none!important}.detail-help{font-size:10px;color:#667;line-height:1.35;margin-top:4px}@media(max-width:800px){.trip-detail-editor{grid-template-columns:1fr 1fr}.trip-detail-editor .wide{grid-column:span 2}}@media(max-width:560px){.trip-detail-editor{grid-template-columns:1fr}.trip-detail-editor .wide,.trip-detail-editor .full{grid-column:1}.camp-toggle{padding:3px 0}}@media print{.trip-stop,.stop-meta,.trip-detail-editor,.trip-summary-card,.trip-notes,.planner-section{break-inside:avoid!important;page-break-inside:avoid!important}.trip-stop{overflow:visible!important}.trip-map-wrap,.trip-detail-actions{display:none!important}}';
  document.head.appendChild(css);

  function decorateStops(){
    const trip=getTrip();if(!trip)return;
    const root=document.getElementById('tripStops');
    if(root&&!document.getElementById('tripDetailActions')){const actions=document.createElement('div');actions.id='tripDetailActions';actions.className='trip-detail-actions';actions.innerHTML='<button id="saveTripDetailsBtn" class="button blue" type="button">Save trip details</button><span id="tripDetailStatus" class="trip-detail-status"></span>';root.parentNode.insertBefore(actions,root);actions.querySelector('#saveTripDetailsBtn').onclick=()=>persistAll(true)}
    document.querySelectorAll('.trip-stop').forEach(stop=>{
      const day=stop.querySelector('.stop-day');if(!day)return;const slug=day.dataset.slug;if(stop.querySelector('.trip-detail-editor'))return;
      const meta=trip.stopMeta&&trip.stopMeta[slug]||{},park=parks.find(p=>p.slug===slug);if(!park)return;const address=parkAddress(park),d=parkDetail(park);
      const box=document.createElement('div');box.className='trip-detail-editor';box.dataset.slug=slug;
      box.innerHTML='<div class="park-address-block wide"><span>Park address</span><div class="park-address-readonly">'+(address?esc(address)+' · <a target="_blank" rel="noopener" href="'+esc(placeUrl(park))+'">Google Maps ↗</a>':'Address not yet verified')+'</div>'+(d.statusNote?'<div class="detail-help">'+esc(d.statusNote)+'</div>':'')+'</div><label><span>Visit date</span><input type="date" class="detail-date" value="'+esc(meta.date||'')+'"></label><label class="camp-toggle"><input type="checkbox" class="camping-here" '+(meta.camping?'checked':'')+'> Camping here</label><label class="camp-extra '+(meta.camping?'':'camp-hidden')+'"><span>Campground</span><input type="text" class="campground-name" value="'+esc(meta.campground||'')+'" placeholder="e.g. River Campground"></label><label class="camp-extra '+(meta.camping?'':'camp-hidden')+'"><span>Loop</span><input type="text" class="campground-loop" value="'+esc(meta.loop||'')+'" placeholder="e.g. Lakeview Loop"></label><label class="camp-extra '+(meta.camping?'':'camp-hidden')+'"><span>Campsite</span><input type="text" class="campsite-number" value="'+esc(meta.campsite||'')+'" placeholder="e.g. Site 24"></label><label class="camp-extra '+(meta.camping?'':'camp-hidden')+'"><span>Reservation #</span><input type="text" class="reservation-number" value="'+esc(meta.reservation||'')+'" placeholder="Confirmation / booking number"></label><label class="camp-extra '+(meta.camping?'':'camp-hidden')+'"><span>Check-in</span><input type="time" class="check-in-time" value="'+esc(meta.checkIn||'')+'"></label><label class="camp-extra '+(meta.camping?'':'camp-hidden')+'"><span>Check-out</span><input type="time" class="check-out-time" value="'+esc(meta.checkOut||'')+'"></label>';
      const metaBox=stop.querySelector('.stop-meta');(metaBox||stop.lastElementChild).insertAdjacentElement('afterend',box);
    });
  }

  document.addEventListener('change',e=>{if(!e.target.classList.contains('camping-here'))return;const box=e.target.closest('.trip-detail-editor');if(box)box.querySelectorAll('.camp-extra').forEach(x=>x.classList.toggle('camp-hidden',!e.target.checked))});

  function persistAll(showStatus=false){
    const trips=read(),trip=trips.find(t=>t.id===id);if(!trip)return false;trip.stopMeta=trip.stopMeta||{};
    const stopEls=[...document.querySelectorAll('.trip-stop')];
    stopEls.forEach((stop,index)=>{const day=stop.querySelector('.stop-day'),slug=day&&day.dataset.slug;if(!slug)return;const editor=stop.querySelector('.trip-detail-editor'),note=stop.querySelector('.stop-note'),prev=trip.stopMeta[slug]||{};trip.stopMeta[slug]={...prev,day:day?day.value.trim():String(prev.day||''),date:editor?.querySelector('.detail-date')?.value||'',order:index+1,note:note?note.value:String(prev.note||''),camping:Boolean(editor?.querySelector('.camping-here')?.checked),campground:editor?.querySelector('.campground-name')?.value.trim()||'',loop:editor?.querySelector('.campground-loop')?.value.trim()||'',campsite:editor?.querySelector('.campsite-number')?.value.trim()||'',reservation:editor?.querySelector('.reservation-number')?.value.trim()||'',checkIn:editor?.querySelector('.check-in-time')?.value||'',checkOut:editor?.querySelector('.check-out-time')?.value||''}});
    write(trips);if(showStatus){const s=document.getElementById('tripDetailStatus');if(s){s.textContent='Trip details saved ✓';setTimeout(()=>s.textContent='',2200)}}return true;
  }
  const stops=document.getElementById('tripStops');if(stops)new MutationObserver(()=>setTimeout(decorateStops,0)).observe(stops,{childList:true,subtree:true});
  decorateStops();
  const saveDays=document.getElementById('saveDayAssignmentsBtn');if(saveDays)saveDays.addEventListener('click',()=>persistAll(false),true);
  const saveTrip=document.getElementById('saveTripBtn');if(saveTrip)saveTrip.addEventListener('click',()=>persistAll(false),true);

  function exportCompact(){
    persistAll(false);const trip=getTrip();if(!trip)return;const groups=grouped(trip),ordered=(trip.parks||[]).map(s=>parks.find(p=>p.slug===s)).filter(Boolean),assigned=groups.filter(g=>g.key!=='Unassigned').length;
    const days=groups.map(g=>'<section class="day"><div class="day-head"><h2>'+(g.key==='Unassigned'?'Unassigned stops':'Day '+esc(g.key))+'</h2><span>'+g.stops.length+' stop'+(g.stops.length===1?'':'s')+'</span></div><a class="route" href="'+mapsUrl(g.stops)+'">'+(g.stops.length===1?'Open park in Google Maps ↗':'Open day route in Google Maps ↗')+'</a>'+g.stops.map((p,i)=>{const m=trip.stopMeta&&trip.stopMeta[p.slug]||{},camp=m.camping?'<div class="camp"><b>Camping:</b> '+esc([m.campground,m.loop,m.campsite].filter(Boolean).join(' · ')||'Yes')+(m.reservation?'<br><b>Reservation:</b> '+esc(m.reservation):'')+((m.checkIn||m.checkOut)?'<br><b>Check-in / out:</b> '+esc(m.checkIn||'—')+' / '+esc(m.checkOut||'—'):'')+'</div>':'',address=parkAddress(p);return '<article class="park"><div class="copy"><div class="title"><b>'+(i+1)+'. '+esc(p.name)+'</b><span>'+esc(p.city)+', '+esc(p.state)+'</span></div>'+(m.date?'<div class="address"><b>Date:</b> '+esc(m.date)+'</div>':'')+(address?'<div class="address"><b>Address:</b> '+esc(address)+'</div>':'')+camp+(m.note?'<div class="note"><b>Trip note:</b> '+esc(m.note)+'</div>':'')+(p.criticalFactors?'<div class="critical"><b>Critical factor:</b> '+esc(p.criticalFactors)+'</div>':'')+'</div></article>'}).join('')+'</section>').join('');
    const html='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(trip.name||'Trip')+' — Trip Plan</title><style>@page{margin:11mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;margin:0;color:#15212b;background:#fff;font-size:10.5px}.cover{border-top:5px solid #00558a;border-bottom:1px solid #d9dfe3;padding:8mm 0 6mm;margin-bottom:6mm;break-inside:avoid;page-break-inside:avoid}.brand{font-size:8px;letter-spacing:.16em;font-weight:800;color:#00558a}.cover h1{font-size:27px;line-height:1;margin:6px 0 4px}.meta{color:#64727e;font-size:10px}.cover-grid{display:flex;gap:24px;margin-top:8px}.cover-grid strong{font-size:17px;color:#00558a}.cover-grid span{display:block;font-size:7px;text-transform:uppercase;letter-spacing:.1em;color:#64727e}.trip-notes{margin:6px 0 0;max-width:680px;line-height:1.3}.day{margin:0 0 5mm}.day-head{display:flex;justify-content:space-between;align-items:end;border-bottom:2px solid #00558a;padding-bottom:3px;margin-bottom:4px}.day h2{font-size:18px;margin:0}.day-head span{color:#64727e;font-size:8px}.route{display:inline-block;color:#00558a;text-decoration:none;font-weight:800;font-size:8px;text-transform:uppercase;margin:0 0 4px}.park{border:1px solid #d9dfe3;margin:0 0 4px;break-inside:avoid;page-break-inside:avoid}.copy{padding:6px 8px;line-height:1.22}.title{display:flex;gap:8px;justify-content:space-between;align-items:baseline}.title b{font-size:12px}.title span{font-size:8px;color:#64727e;white-space:nowrap}.address,.camp,.note,.critical{margin-top:3px;font-size:8.5px}.camp{background:#f4f1e9;padding:3px 5px;border-left:3px solid #00558a}.critical{color:#7d4b36}.footer{border-top:1px solid #d9dfe3;padding-top:4px;color:#64727e;font-size:7px;margin-top:3mm}.print-note{font-size:8px;color:#64727e;margin-bottom:4mm}@media print{.print-note{display:none}.cover,.park{break-inside:avoid!important;page-break-inside:avoid!important}}</style></head><body><header class="cover"><div class="brand">MINNESOTA + WISCONSIN STATE PARKS</div><h1>'+esc(trip.name||'Trip Plan')+'</h1><div class="meta">'+(trip.date?esc(trip.date):'Trip plan')+'</div>'+(trip.notes?'<div class="trip-notes">'+esc(trip.notes)+'</div>':'')+'<div class="cover-grid"><div><strong>'+ordered.length+'</strong><span>Parks</span></div><div><strong>'+assigned+'</strong><span>Assigned days</span></div><div><strong>'+groups.length+'</strong><span>Itinerary groups</span></div></div></header><main><p class="print-note">Use Print / Save as PDF to create the PDF.</p>'+days+'<footer class="footer">Generated from the MN & WI State Parks trip planner. Verify current conditions, closures, reservations and access before travel.</footer></main><script>addEventListener("load",()=>setTimeout(()=>print(),500));<\/script></body></html>';
    const w=window.open('','_blank');if(!w){alert('Please allow pop-ups to export the trip PDF.');return}w.document.open();w.document.write(html);w.document.close();
  }
  window.TripCompactExport=exportCompact;
  const printBtn=document.getElementById('printTripBtn');if(printBtn&&!window.TripBookletExport){printBtn.textContent='Export trip PDF';printBtn.onclick=exportCompact}
})();
